# Generated by Django 4.2.6 on 2023-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0003_restauranttables_tablestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdrinksorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Table Number'),
        ),
        migrations.AddField(
            model_name='restaurantfoodorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Table Number'),
        ),
    ]
