# Generated by Django 4.1.3 on 2023-10-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0002_remove_hoteldrinkscategories_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
