# Generated by Django 4.2.6 on 2023-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0004_hotelcustomers_customeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproductsunit',
            name='Unit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit'),
        ),
    ]
