# Generated by Django 4.2.6 on 2023-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0009_hotelfoodorder_pending_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteltables',
            name='TableStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Table Status'),
        ),
    ]
