# Generated by Django 4.2.6 on 2023-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0010_hoteltables_tablestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldrinksorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorder',
            name='items',
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='pending_total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Pending Total Price'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='room_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Room Number'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Table Number'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='true_total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='True Total Price'),
        ),
    ]
