# Generated by Django 4.2.6 on 2023-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0011_remove_hoteldrinksorder_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldrinksorderitems',
            name='is_customer_closed',
        ),
        migrations.RemoveField(
            model_name='hoteldrinksorderitems',
            name='is_customer_opened',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorderitems',
            name='is_customer_closed',
        ),
        migrations.RemoveField(
            model_name='hotelfoodorderitems',
            name='is_customer_opened',
        ),
        migrations.RemoveField(
            model_name='hotelroomsorderitems',
            name='is_customer_closed',
        ),
        migrations.RemoveField(
            model_name='hotelroomsorderitems',
            name='is_customer_opened',
        ),
        migrations.AddField(
            model_name='hotelroomsorderitems',
            name='is_customer_opened_closed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Customer Opened/Closed Status'),
        ),
    ]
