# Generated by Django 4.2.6 on 2023-11-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0014_hotelotherscart_hotelotherscategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of days'),
        ),
        migrations.AddField(
            model_name='hoteldrinksorder',
            name='room_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Room Price'),
        ),
        migrations.AddField(
            model_name='hotelfoodorder',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of days'),
        ),
        migrations.AddField(
            model_name='hotelfoodorder',
            name='room_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Room Price'),
        ),
    ]
